### ISSUE TITLE
Update copyright notice

### ISSUE THREAD

**Issue by davelab6** [typeoff/martel#2]
- [x] Copyright notice should be `Copyright (c) 2015 Dan Reynolds. Copyright (c) 2010-2015, Sorkin Type Co (www.sorkintype.com) with Reserved Font Name 'Merriweather'` in OFL.txt and in all files

**Comment by typeoff** [comment]
Thanks!

Where in the font’s header shook the RFN be stored? In the font note, in the font description, somewhere else?

**Comment by davelab6** [comment]
The copyright notice should be a single line, in the `Copyright` field

**Comment by typeoff** [comment]
OK, I get it now. Thanks!

**Comment by typeoff** [comment]
Updated!
